"""empty message

Revision ID: cc855ed236a
Revises: None
Create Date: 2015-01-31 17:40:15.054706

"""

# revision identifiers, used by Alembic.
revision = 'cc855ed236a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rb_breweries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('google_id', sa.String(length=50), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('cellars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rb_beers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ratebeer_id', sa.Integer(), nullable=True),
    sa.Column('short_name', sa.String(length=255), nullable=False),
    sa.Column('brewery_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(), nullable=False),
    sa.Column('num', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['brewery_id'], ['rb_breweries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bottles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('size', sa.Numeric(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('batch_no', sa.String(), nullable=True),
    sa.Column('brew_date', sa.Date(), nullable=True),
    sa.Column('best_before_date', sa.Date(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('date_removed', sa.Date(), nullable=True),
    sa.Column('beer_id', sa.Integer(), nullable=False),
    sa.Column('cellar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beer_id'], ['rb_beers.id'], ),
    sa.ForeignKeyConstraint(['cellar_id'], ['cellars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bottles')
    op.drop_table('rb_beers')
    op.drop_table('cellars')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('rb_breweries')
    ### end Alembic commands ###
