---
  - name: install nginx
    apt: pkg=nginx state=latest

  - name: copy nginx sites
    template: src=nginx.j2
              dest=/etc/nginx/sites-available/{{app.name}}
              owner=root
              group=root
              mode=0644
    notify:
      - restart nginx

  - name: enable nginx sites
    file: src=/etc/nginx/sites-available/{{app.name}}
          dest=/etc/nginx/sites-enabled/{{app.name}}
          owner=root
          group=root
          state=link
    notify:
      - restart nginx

  - name: disable default site
    file: path=/etc/nginx/sites-enabled/default
          state=absent
    notify:
      - restart nginx

  - name: make sure nginx is running
    service: name=nginx state=running enabled=yes